name: Code Quality

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
          pip install flake8
          pip install pylint
          pip install bandit
          pip install codecov
          pip install -r requirements.txt
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: |
          flake8 src
          pylint src --fail-under=9
  unit-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: pytest
  static-analisys:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: bandit src